language: php

php:
  - 7.1

dist: trusty

services:
  - postgresql

before_script:
  - psql -c 'create database meetingdb;' -U postgres
  - cp .env.config .env
  - composer install
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit
