language: php

php:
  - 7.1

dist: trusty

services:
  - postgresql

addons:
  postgresql: "11.2"
  apt:
    packages:
      - postgresql-11

before_script:
  - psql -c 'create database meetingdb;' -U postgres
  - copy .env.config .env
  - composer install
  - php artisan key:generate
  - artisan migrate

script:
  - vendor/bin/phpunit
