language: php

php:
  - 7.1

dist: trusty

services:
  - postgresql

addons:
  postgresql: 11
  apt:
    packages:
      - postgresql-11-postgis-2.4

before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -c 'create database meetingdb;' -U postgres
  - cp .env.travis .env
  - composer install
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit
