language: php

php:
  - 7.1

dist: bionic

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS meetingdb;'
  - cp .env.travis .env
  - composer install
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit
