version: '3'

services:
    web:
        container_name: meeting_web
        build: .
        ports:
            - "80:80"
        depends_on:
            - db
        volumes:
            - ./:/var/www/html
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        env_file:
            - .env.config
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "discovery.type=single-node"
            - "xpack.security.enabled=false"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
            - "9300:9300"
    kibana:
        image: docker.elastic.co/kibana/kibana:7.3.0
        ports:
            - "5601:5601"
        depends_on:
           - elasticsearch
